In [1]:
import pandas as pd
import os
from dotenv import load_dotenv

# Load environment variables (override existing)
load_dotenv(override=True)

True

In [2]:
# Get paths from environment variables
from urllib.parse import unquote

base_path = os.getenv('HTML_PATH')
download_path = os.getenv('DOWNLOAD_PATH')

# Handle file:// URI format - convert to regular path
if base_path.startswith('file:///'):
    # Remove file:/// prefix and decode URL encoding (e.g., %20 -> space, %25 -> %)
    path = unquote(base_path[8:])  # Remove 'file:///' - this is already the full file path
elif os.path.isfile(base_path):
    # If base_path is already a file, use it directly
    path = base_path
else:
    # If it's a directory, join with filename
    path = os.path.join(base_path, "DetailedStatement.htm")

In [3]:
# Check if file exists before reading
if not os.path.exists(path):
    print(f"Error: HTML file not found at path")
else:
    # Read HTML file
    tables = pd.read_html(path)
    
    # Check if tables are found
    if not tables:
        print("No tables found in the HTML file.")
    else:
        print(f"Found {len(tables)} tables in the HTML file.")
        for i, table in enumerate(tables, 1):
            print(f"Table {i}: {table.shape[0]} rows x {table.shape[1]} columns")

Found 1 tables in the HTML file.
Table 1: 9246 rows x 22 columns

In [4]:
def html_to_excel(html_file, excel_file):
    try:
        # Read HTML tables from the file
        tables = pd.read_html(html_file)
        if not tables:
            print("No tables found in the HTML file.")
            return
        
        # Save each table to a separate sheet in Excel
        with pd.ExcelWriter(excel_file, engine='openpyxl') as writer:
            for idx, table in enumerate(tables, start=1):
                sheet_name = f"Sheet{idx}"
                table.to_excel(writer, sheet_name=sheet_name, index=False)
        
        print(f"Conversion successful!")
    
    except FileNotFoundError:
        print(f"Error: File '{html_file}' not found.")
    except ValueError as e:
        print(f"Error reading HTML: {e}")
    except Exception as e:
        print(f"Unexpected error: {e}")

# Convert the HTML file to Excel
if os.path.exists(path):
    excel_output = os.path.join(download_path, "converted_tables.xlsx")
    html_to_excel(path, excel_output)
else:
    print("Cannot convert: HTML file not found.")

Conversion successful!

In [5]:
# read converted csv file
df = pd.read_excel(excel_output, sheet_name='Sheet1')
df.head(10)

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,...,Trade History Report,Trade History Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Name:,Name:,Name:,Name:,FHS-20K Simone Calligaro,FHS-20K Simone Calligaro,FHS-20K Simone Calligaro,FHS-20K Simone Calligaro,FHS-20K Simone Calligaro,FHS-20K Simone Calligaro,...,FHS-20K Simone Calligaro,FHS-20K Simone Calligaro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Account:,Account:,Account:,Account:,"24251276 (USD, FivePercentOnline-Real, real, H...","24251276 (USD, FivePercentOnline-Real, real, H...","24251276 (USD, FivePercentOnline-Real, real, H...","24251276 (USD, FivePercentOnline-Real, real, H...","24251276 (USD, FivePercentOnline-Real, real, H...","24251276 (USD, FivePercentOnline-Real, real, H...",...,"24251276 (USD, FivePercentOnline-Real, real, H...","24251276 (USD, FivePercentOnline-Real, real, H...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Company:,Company:,Company:,Company:,Five Percent Online Ltd,Five Percent Online Ltd,Five Percent Online Ltd,Five Percent Online Ltd,Five Percent Online Ltd,Five Percent Online Ltd,...,Five Percent Online Ltd,Five Percent Online Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Date:,Date:,Date:,Date:,2025.12.31 15:19,2025.12.31 15:19,2025.12.31 15:19,2025.12.31 15:19,2025.12.31 15:19,2025.12.31 15:19,...,2025.12.31 15:19,2025.12.31 15:19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Positions,Positions,Positions,Positions,Positions,Positions,Positions,Positions,Positions,Positions,...,Positions,Positions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Time,Position,Symbol,Type,Volume,Price,S / L,T / P,Time,Price,...,Profit,Profit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2024.08.07 13:40:38,261181889,US30,buy,NaN,NaN,NaN,NaN,NaN,NaN,...,0.01,39338.10,38000.00,NaN,2024.08.07 13:40:51,39337.10,-0.02,0.0,-0.10,-0.10
9,2024.08.08 04:00:02,261467925,US30,buy,505028,505028,505028,505028,505028,505028,...,0.02,38677.50,38455.74,39176.82,2024.08.08 16:52:49,39176.82,-0.04,0.0,99.86,99.86

In [6]:
"""conditions always valid"""

# keep rows from row 2
df = df.iloc[7:].reset_index(drop=True)

# RangeIndex have the corrected column names
df.columns = df.iloc[0]
df = df[1:]

# there are two columns with the same name 'Price'
# rename the second 'Price' column to 'Price2'
df.columns = df.columns.where(df.columns.duplicated() == False, df.columns + '2')

# trim whitespace from column names
df.columns = df.columns.str.strip()

# # trim Profit column values
# df['Profit'] = df['Profit'].str.strip()

# # replace empty characters with '' in 'Profit' column
# df['Profit'] = df['Profit'].replace(r'^\s*$', '', regex=True)

#  drop 'Taxes' column
df = df.drop(columns=['Taxes'], errors='ignore')

df.head()

,Time,Position,Symbol,Type,Volume,Price,S / L,T / P,Time2,Price2,...,Profit,Profit2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024.08.07 13:40:38,261181889,US30,buy,NaN,NaN,NaN,NaN,NaN,NaN,...,0.01,39338.10,38000.00,NaN,2024.08.07 13:40:51,39337.10,-0.02,0.00,-0.10,-0.10
2,2024.08.08 04:00:02,261467925,US30,buy,505028,505028,505028,505028,505028,505028,...,0.02,38677.50,38455.74,39176.82,2024.08.08 16:52:49,39176.82,-0.04,0.00,99.86,99.86
3,2024.08.09 12:00:00,262076026,US30,buy,505035,505035,505035,505035,505035,505035,...,0.02,39564.10,39376.30,39806.72,2024.08.09 15:31:47,39374.90,-0.04,0.00,-37.84,-37.84
4,2024.08.09 12:00:00,262076027,SP500,buy,69038,69038,69038,69038,69038,69038,...,0.01,5344.10,5257.06,5433.40,2024.08.13 22:49:34,5433.40,-0.02,-0.44,8.93,8.93
5,2024.08.09 16:00:00,262169269,US30,sell,505026,505026,505026,505026,505026,505026,...,0.02,39384.40,39559.44,39103.24,2024.08.09 20:16:56,39559.50,-0.04,0.00,-35.02,-35.02

In [7]:
"""
Check case by case the following conditions:
"""
# drop columns 'Volume', 'Price', 'S / L', 'T / P', 'Time2', 'Price2', 'Commission', 'Swap'
df = df.drop(columns=['Volume', 'Price', 'S / L', 'T / P', 'Time2', 'Price2', 'Commission', 'Swap'], errors='ignore')
df.head()

,Time,Position,Symbol,Type,Profit,Profit2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024.08.07 13:40:38,261181889,US30,buy,0.01,39338.10,38000.00,NaN,2024.08.07 13:40:51,39337.10,-0.02,0.00,-0.10,-0.10
2,2024.08.08 04:00:02,261467925,US30,buy,0.02,38677.50,38455.74,39176.82,2024.08.08 16:52:49,39176.82,-0.04,0.00,99.86,99.86
3,2024.08.09 12:00:00,262076026,US30,buy,0.02,39564.10,39376.30,39806.72,2024.08.09 15:31:47,39374.90,-0.04,0.00,-37.84,-37.84
4,2024.08.09 12:00:00,262076027,SP500,buy,0.01,5344.10,5257.06,5433.40,2024.08.13 22:49:34,5433.40,-0.02,-0.44,8.93,8.93
5,2024.08.09 16:00:00,262169269,US30,sell,0.02,39384.40,39559.44,39103.24,2024.08.09 20:16:56,39559.50,-0.04,0.00,-35.02,-35.02

In [11]:
wrong_names = df.columns
wrong_names

Index([    'Time', 'Position',   'Symbol',     'Type',   'Profit',  'Profit2',
              nan,        nan,        nan,        nan,        nan,        nan,
              nan,        nan],
      dtype='object', name=0)

In [12]:
# list of correct names: Time	Position	Symbol	Type	Volume	Price	S / L	T / P	Time	Price	Commission	Swap	Profit
correct_names = ['Time', 'Position', 'Symbol', 'Type', 'Volume', 'Price', 'S / L', 'T / P', 'Time', 'Price', 'Commission', 'Swap', 'Profit']

In [ ]:
"""
Check case by case the following conditions:
"""
# rename columns from wrong_names to correct_names
df = df.rename(columns={

In [ ]:
df.head()

,Open Time,Position,Symbol,Type,Profit,Profit2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024.08.07 13:40:38,261181889,US30,buy,0.01,39338.10,38000.00,NaN,2024.08.07 13:40:51,39337.10,-0.02,0.00,-0.10,-0.10
2,2024.08.08 04:00:02,261467925,US30,buy,0.02,38677.50,38455.74,39176.82,2024.08.08 16:52:49,39176.82,-0.04,0.00,99.86,99.86
3,2024.08.09 12:00:00,262076026,US30,buy,0.02,39564.10,39376.30,39806.72,2024.08.09 15:31:47,39374.90,-0.04,0.00,-37.84,-37.84
4,2024.08.09 12:00:00,262076027,SP500,buy,0.01,5344.10,5257.06,5433.40,2024.08.13 22:49:34,5433.40,-0.02,-0.44,8.93,8.93
5,2024.08.09 16:00:00,262169269,US30,sell,0.02,39384.40,39559.44,39103.24,2024.08.09 20:16:56,39559.50,-0.04,0.00,-35.02,-35.02

In [ ]:
df.shape

(9237, 14)

In [ ]:
df.tail(20)

,Open Time,Position,Symbol,Type,Profit,Profit2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9218,Credit Facility:,Credit Facility:,Credit Facility:,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9219,Floating P/L:,Floating P/L:,Floating P/L:,10.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9220,Equity:,Equity:,Equity:,18 713.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9223,Results,Results,Results,Results,Results,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9224,Total Net Profit:,Total Net Profit:,Total Net Profit:,-515.37,-11 382.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9225,Profit Factor:,Profit Factor:,Profit Factor:,0.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9226,Recovery Factor:,Recovery Factor:,Recovery Factor:,-0.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9227,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9228,Balance Drawdown:,Balance Drawdown:,Balance Drawdown:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9229,Balance Drawdown Absolute:,Balance Drawdown Absolute:,Balance Drawdown Absolute:,548.91,6.85% (1 442.84),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9231,Total Trades:,Total Trades:,Total Trades:,1804,1514 (55.68%),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9232,NaN,NaN,NaN,NaN,801 (44.40%),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9233,NaN,NaN,NaN,NaN,-135.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9234,NaN,NaN,NaN,NaN,-14.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9235,NaN,NaN,NaN,NaN,20 (-327.66),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9236,NaN,NaN,NaN,NaN,-342.51 (4),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9237,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
-

SyntaxError: invalid syntax (476313318.py, line 1)

In [ ]:
# ==================================================================
"""
from df.tail() check first row with SumSummary:	Summary:	Summary:
cancel all rows from that row onwards, indicating the RangeIndex num
"""
# ==================================================================

'\nfrom df.tail() check first row with SumSummary:\tSummary:\tSummary:\ncancel all rows from that row onwards, indicating the RangeIndex num\n'

In [ ]:
"""conditions depending on data, check data length first"""
# drop rows indicating correct RangeIndex (with iloc)
up_to_row = 1356  # adjust this number based on actual data
df = df.iloc[:up_to_row]

In [ ]:
df.tail(10)

In [ ]:
"""conditions always valid"""

"""
drop rows where 'Open Time' and 'Close Time' have the following values:
Closed P/L:
Open Trades:
Open Time
Working Orders:
No transactions
0.00
""";
# drop strings in 'Open Time' and 'Close Time' columns
strings_to_drop = ['Closed P/L:', 'Open Trades:', 'Open Time', 'Working Orders:', 'No transactions', '0.00']
df = df[~df['Open Time'].isin(strings_to_drop)]
df = df[~df['Close Time'].isin(strings_to_drop)]

"""
drop rows where 'Type' have the following values:
balance
""";
# drop strings in 'Type' column
df = df[~df['Type'].isin(['balance'])]

# drop rows where 'Ticket' is nan
df = df.dropna(subset=['Ticket'])

In [ ]:
"""
drop rows where 'Commission' contains the following values:
cancelled
Floating P/L:
"from #"
"Portfolio"
"folio"  
"to #"
[tp]
[sl]
""";

# drop rows where Commission column contains any of these strings
strings_to_drop_commission = ['cancelled', 'Floating P/L:', 'from #', 'Portfolio', 'folio', 'to #', '[tp]', '[sl]']

# Use str.contains with regex OR pattern to match any of the strings
pattern = '|'.join(strings_to_drop_commission)
df = df[~df['Commission'].str.contains(pattern, case=False, na=False)]

In [ ]:
# # print df.Commission.unique()
# print(df.Commission.unique())

In [ ]:
# convert Open Time and Close Time to datetime
df['Open Time'] = pd.to_datetime(df['Open Time'])
df['Close Time'] = pd.to_datetime(df['Close Time'])

# drop rows where 'Open Time' is nan
df = df.dropna(subset=['Open Time'])

# replace rows where 'Close Time' is nan with 'Close Time' = 'Open Time' + 4 hours
df['Close Time'] = df['Close Time'].fillna(df['Open Time'] + pd.Timedelta(hours=4))

In [ ]:
# df.head()

In [ ]:
# df.tail(20)

In [ ]:
# # print df.Profit.unique()
# print(df.Profit.unique())

In [ ]:
# clean Profit column before converting to float
# remove spaces used as thousands separators
df['Profit'] = df['Profit'].astype(str).str.replace(' ', '', regex=False)

# convert cleaned dataframe to proper Dtypes
df = df.astype({
    'Size': 'float64',
    # check if 'Ticket' can be converted to int, if not use 'str' instead
    'Ticket': 'int64',
    'S / L': 'float64',
    'T / P': 'float64',
    'Price': 'float64',
    'Price2': 'float64',
    'Commission': 'float64',
    'Swap': 'float64',
    'Profit': 'float64'
})

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 671 entries, 1 to 1344
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Ticket      671 non-null    int64
 1   Open Time   671 non-null    datetime64[ns]
 2   Type        671 non-null    object
 3   Size        671 non-null    float64
 4   Item        671 non-null    object
 5   Price       671 non-null    float64
 6   S / L       671 non-null    float64
 7   T / P       671 non-null    float64
 8   Close Time  671 non-null    datetime64[ns]
 9   Price2      671 non-null    float64
 10  Commission  671 non-null    float64
 11  Swap        671 non-null    float64
 12  Profit      671 non-null    float64
dtypes: datetime64[ns](2), float64(8), int64(1), object(2)
memory usage: 73.4+ KB

In [ ]:
# print shape of cleaned dataframe
print(f"Cleaned DataFrame shape: {df.shape}")

# print column names
print("Column names:", df.columns.tolist())

Cleaned DataFrame shape: (671, 13)
Column names: ['Ticket', 'Open Time', 'Type', 'Size', 'Item', 'Price', 'S / L', 'T / P', 'Close Time', 'Price2', 'Commission', 'Swap', 'Profit']

In [ ]:
# ==================================================================
"""
rename cleaned dataframe to clean Excel file name in the next cell
""";
# ==================================================================

In [ ]:
# download cleaned dataframe to excel
cleaned_excel_output = os.path.join(download_path, "cleaned_excel_output.xlsx")

df.to_excel(cleaned_excel_output, index=False)