In [52]:
import pandas as pd
import os
from dotenv import load_dotenv

# Load environment variables (override existing)
load_dotenv(override=True)

True

In [53]:
# Get paths from environment variables
from urllib.parse import unquote

base_path = os.getenv('HTML_PATH')
download_path = os.getenv('DOWNLOAD_PATH')

# Handle file:// URI format - convert to regular path
if base_path.startswith('file:///'):
    # Remove file:/// prefix and decode URL encoding (e.g., %20 -> space, %25 -> %)
    path = unquote(base_path[8:])  # Remove 'file:///' - this is already the full file path
elif os.path.isfile(base_path):
    # If base_path is already a file, use it directly
    path = base_path
else:
    # If it's a directory, join with filename
    path = os.path.join(base_path, "DetailedStatement.htm")

In [54]:
# Check if file exists before reading
if not os.path.exists(path):
    print(f"Error: HTML file not found at path")
else:
    # Read HTML file
    tables = pd.read_html(path)
    
    # Check if tables are found
    if not tables:
        print("No tables found in the HTML file.")
    else:
        print(f"Found {len(tables)} tables in the HTML file.")
        for i, table in enumerate(tables, 1):
            print(f"Table {i}: {table.shape[0]} rows x {table.shape[1]} columns")

Found 1 tables in the HTML file.
Table 1: 9246 rows x 22 columns

In [55]:
def html_to_excel(html_file, excel_file):
    try:
        # Read HTML tables from the file
        tables = pd.read_html(html_file)
        if not tables:
            print("No tables found in the HTML file.")
            return
        
        # Save each table to a separate sheet in Excel
        with pd.ExcelWriter(excel_file, engine='openpyxl') as writer:
            for idx, table in enumerate(tables, start=1):
                sheet_name = f"Sheet{idx}"
                table.to_excel(writer, sheet_name=sheet_name, index=False)
        
        print(f"Conversion successful!")
    
    except FileNotFoundError:
        print(f"Error: File '{html_file}' not found.")
    except ValueError as e:
        print(f"Error reading HTML: {e}")
    except Exception as e:
        print(f"Unexpected error: {e}")

# Convert the HTML file to Excel
if os.path.exists(path):
    excel_output = os.path.join(download_path, "converted_tables.xlsx")
    html_to_excel(path, excel_output)
else:
    print("Cannot convert: HTML file not found.")

Conversion successful!

In [56]:
# read converted csv file
df = pd.read_excel(excel_output, sheet_name='Sheet1')
df.head(10)

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,...,Trade History Report,Trade History Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Name:,Name:,Name:,Name:,FHS-20K Simone Calligaro,FHS-20K Simone Calligaro,FHS-20K Simone Calligaro,FHS-20K Simone Calligaro,FHS-20K Simone Calligaro,FHS-20K Simone Calligaro,...,FHS-20K Simone Calligaro,FHS-20K Simone Calligaro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Account:,Account:,Account:,Account:,"24251276 (USD, FivePercentOnline-Real, real, H...","24251276 (USD, FivePercentOnline-Real, real, H...","24251276 (USD, FivePercentOnline-Real, real, H...","24251276 (USD, FivePercentOnline-Real, real, H...","24251276 (USD, FivePercentOnline-Real, real, H...","24251276 (USD, FivePercentOnline-Real, real, H...",...,"24251276 (USD, FivePercentOnline-Real, real, H...","24251276 (USD, FivePercentOnline-Real, real, H...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Company:,Company:,Company:,Company:,Five Percent Online Ltd,Five Percent Online Ltd,Five Percent Online Ltd,Five Percent Online Ltd,Five Percent Online Ltd,Five Percent Online Ltd,...,Five Percent Online Ltd,Five Percent Online Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Date:,Date:,Date:,Date:,2025.12.31 15:19,2025.12.31 15:19,2025.12.31 15:19,2025.12.31 15:19,2025.12.31 15:19,2025.12.31 15:19,...,2025.12.31 15:19,2025.12.31 15:19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Positions,Positions,Positions,Positions,Positions,Positions,Positions,Positions,Positions,Positions,...,Positions,Positions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Time,Position,Symbol,Type,Volume,Price,S / L,T / P,Time,Price,...,Profit,Profit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2024.08.07 13:40:38,261181889,US30,buy,NaN,NaN,NaN,NaN,NaN,NaN,...,0.01,39338.10,38000.00,NaN,2024.08.07 13:40:51,39337.10,-0.02,0.0,-0.10,-0.10
9,2024.08.08 04:00:02,261467925,US30,buy,505028,505028,505028,505028,505028,505028,...,0.02,38677.50,38455.74,39176.82,2024.08.08 16:52:49,39176.82,-0.04,0.0,99.86,99.86

In [57]:
df.shape

(9245, 22)

In [58]:
# drop columns index 4 to 11
df.drop(df.columns[4:12], axis=1, inplace=True)
df.head(10)

,0,1,2,3,12,13,14,15,16,17,18,19,20,21
0,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Name:,Name:,Name:,Name:,FHS-20K Simone Calligaro,FHS-20K Simone Calligaro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Account:,Account:,Account:,Account:,"24251276 (USD, FivePercentOnline-Real, real, H...","24251276 (USD, FivePercentOnline-Real, real, H...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Company:,Company:,Company:,Company:,Five Percent Online Ltd,Five Percent Online Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Date:,Date:,Date:,Date:,2025.12.31 15:19,2025.12.31 15:19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Positions,Positions,Positions,Positions,Positions,Positions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Time,Position,Symbol,Type,Profit,Profit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2024.08.07 13:40:38,261181889,US30,buy,0.01,39338.10,38000.00,NaN,2024.08.07 13:40:51,39337.10,-0.02,0.0,-0.10,-0.10
9,2024.08.08 04:00:02,261467925,US30,buy,0.02,38677.50,38455.74,39176.82,2024.08.08 16:52:49,39176.82,-0.04,0.0,99.86,99.86

In [59]:
df.shape

(9245, 14)

In [60]:
# keep df from row 8 only
df = df.iloc[8:]
df.head(10)

,0,1,2,3,12,13,14,15,16,17,18,19,20,21
8,2024.08.07 13:40:38,261181889,US30,buy,0.01,39338.10,38000.00,NaN,2024.08.07 13:40:51,39337.10,-0.02,0.00,-0.10,-0.10
9,2024.08.08 04:00:02,261467925,US30,buy,0.02,38677.50,38455.74,39176.82,2024.08.08 16:52:49,39176.82,-0.04,0.00,99.86,99.86
10,2024.08.09 12:00:00,262076026,US30,buy,0.02,39564.10,39376.30,39806.72,2024.08.09 15:31:47,39374.90,-0.04,0.00,-37.84,-37.84
11,2024.08.09 12:00:00,262076027,SP500,buy,0.01,5344.10,5257.06,5433.40,2024.08.13 22:49:34,5433.40,-0.02,-0.44,8.93,8.93
12,2024.08.09 16:00:00,262169269,US30,sell,0.02,39384.40,39559.44,39103.24,2024.08.09 20:16:56,39559.50,-0.04,0.00,-35.02,-35.02
13,2024.08.09 20:00:00,262295775,US30,sell,0.02,39477.85,39665.65,39235.23,2024.08.12 04:00:00,39458.80,-0.04,-5.00,3.81,3.81
14,2024.08.12 04:00:00,262434487,US30,buy,0.02,39458.80,39241.18,39868.20,2024.08.12 16:57:30,39240.30,-0.04,0.00,-43.70,-43.70
15,2024.08.12 08:00:11,262472731,US30,buy,0.02,39498.50,39277.74,39998.82,2024.08.12 16:53:12,39276.80,-0.04,0.00,-44.34,-44.34
16,2024.08.12 16:00:00,262642893,US30,buy,0.02,39564.40,39333.80,39866.30,2024.08.12 16:47:14,39333.80,-0.04,0.00,-46.12,-46.12
17,2024.08.13 04:00:00,262872616,US30,buy,0.01,39406.60,39181.95,39701.68,2024.08.13 19:21:28,39701.68,-0.02,0.00,29.51,29.51

In [61]:
# Columns are already correctly named in the previous cell
df.columns.tolist()

[0, 1, 2, 3, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [62]:
# rename columns to Time	Position	Symbol	Type	Volume	Price	S / L	T / P	Time	Price	Commission	Swap	Profit Extra
df.columns = ['Time', 'Position', 'Symbol', 'Type', 'Volume', 'Price', 'S / L', 'T / P', 'Time2', 'Price2', 'Commission', 'Swap', 'Profit', 'Extra']
df.head(10)

,Time,Position,Symbol,Type,Volume,Price,S / L,T / P,Time2,Price2,Commission,Swap,Profit,Extra
8,2024.08.07 13:40:38,261181889,US30,buy,0.01,39338.10,38000.00,NaN,2024.08.07 13:40:51,39337.10,-0.02,0.00,-0.10,-0.10
9,2024.08.08 04:00:02,261467925,US30,buy,0.02,38677.50,38455.74,39176.82,2024.08.08 16:52:49,39176.82,-0.04,0.00,99.86,99.86
10,2024.08.09 12:00:00,262076026,US30,buy,0.02,39564.10,39376.30,39806.72,2024.08.09 15:31:47,39374.90,-0.04,0.00,-37.84,-37.84
11,2024.08.09 12:00:00,262076027,SP500,buy,0.01,5344.10,5257.06,5433.40,2024.08.13 22:49:34,5433.40,-0.02,-0.44,8.93,8.93
12,2024.08.09 16:00:00,262169269,US30,sell,0.02,39384.40,39559.44,39103.24,2024.08.09 20:16:56,39559.50,-0.04,0.00,-35.02,-35.02
13,2024.08.09 20:00:00,262295775,US30,sell,0.02,39477.85,39665.65,39235.23,2024.08.12 04:00:00,39458.80,-0.04,-5.00,3.81,3.81
14,2024.08.12 04:00:00,262434487,US30,buy,0.02,39458.80,39241.18,39868.20,2024.08.12 16:57:30,39240.30,-0.04,0.00,-43.70,-43.70
15,2024.08.12 08:00:11,262472731,US30,buy,0.02,39498.50,39277.74,39998.82,2024.08.12 16:53:12,39276.80,-0.04,0.00,-44.34,-44.34
16,2024.08.12 16:00:00,262642893,US30,buy,0.02,39564.40,39333.80,39866.30,2024.08.12 16:47:14,39333.80,-0.04,0.00,-46.12,-46.12
17,2024.08.13 04:00:00,262872616,US30,buy,0.01,39406.60,39181.95,39701.68,2024.08.13 19:21:28,39701.68,-0.02,0.00,29.51,29.51

In [63]:
# print sum of Profit and Extra columns to compare values
print("Sum of Profit column:", df['Profit'].sum())
print("Sum of Extra column:", df['Extra'].sum())

Sum of Profit column: 158.59000000000026
Sum of Extra column: 158.59000000000026

In [64]:
# drop column Extra if Sum of Profit column and Sum of Extra column are the same
if df['Profit'].sum() == df['Extra'].sum():
    df.drop(columns=['Extra'], inplace=True)

# rename Time to Open Time and Time2 to Close Time
df.rename(columns={'Time': 'Open Time', 'Time2': 'Close Time'}, inplace=True)

In [65]:
df.head()

,Open Time,Position,Symbol,Type,Volume,Price,S / L,T / P,Close Time,Price2,Commission,Swap,Profit
8,2024.08.07 13:40:38,261181889,US30,buy,0.01,39338.10,38000.00,NaN,2024.08.07 13:40:51,39337.10,-0.02,0.00,-0.10
9,2024.08.08 04:00:02,261467925,US30,buy,0.02,38677.50,38455.74,39176.82,2024.08.08 16:52:49,39176.82,-0.04,0.00,99.86
10,2024.08.09 12:00:00,262076026,US30,buy,0.02,39564.10,39376.30,39806.72,2024.08.09 15:31:47,39374.90,-0.04,0.00,-37.84
11,2024.08.09 12:00:00,262076027,SP500,buy,0.01,5344.10,5257.06,5433.40,2024.08.13 22:49:34,5433.40,-0.02,-0.44,8.93
12,2024.08.09 16:00:00,262169269,US30,sell,0.02,39384.40,39559.44,39103.24,2024.08.09 20:16:56,39559.50,-0.04,0.00,-35.02

In [66]:
df.shape

(9237, 13)

In [67]:
"""
Check case by case the following conditions:
"""
# 478733279 is currently the last open position in the html statement
# print row where Ticket is 478733279
df[df['Position'].astype(str) == '478733279']

,Open Time,Position,Symbol,Type,Volume,Price,S / L,T / P,Close Time,Price2,Commission,Swap,Profit
1791,2025.12.29 14:00:00,478733279,US30,buy,0.02,48716.12,48693.06,48809.06,2025.12.29 14:05:20,48693.18,0.0,0.0,-0.46
5600,2025.12.29 14:00:00,478733279,US30,buy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
"""
Check case by case the following conditions:
"""

# keep rows up to 1783
df = df.iloc[:1783].reset_index(drop=True)

In [76]:
df.tail(10)

,Open Time,Position,Symbol,Type,Volume,Price,S / L,T / P,Close Time,Price2,Commission,Swap,Profit
1773,2025.12.11 04:00:00,471701268,SP500,buy,0.2,6864.26,6803.16,NaN,2025.12.12 18:38:15,6802.64,0.0,-0.24,-12.32
1774,2025.12.11 05:00:01,471728151,SP500,sell,0.2,6844.74,6905.98,6754.93,2025.12.11 23:06:18,6905.95,0.0,0.00,-12.24
1775,2025.12.11 18:00:00,472196779,SP500,buy,0.2,6868.36,6805.25,6945.29,2025.12.12 18:37:53,6804.84,0.0,-0.24,-12.70
1776,2025.12.12 05:00:02,472381926,SP500,buy,0.2,6906.56,6843.19,NaN,2025.12.12 17:30:04,6842.73,0.0,0.00,-12.77
1777,2025.12.12 18:00:00,472842578,SP500,sell,0.2,6825.75,6895.96,NaN,2025.12.19 22:00:00,6835.27,0.0,-1.68,-1.90
1778,2025.12.15 17:00:00,473463511,SP500,buy,0.2,6834.05,6773.86,NaN,2025.12.16 09:44:06,6773.75,0.0,-0.24,-12.06
1779,2025.12.17 20:00:00,474851918,SP500,sell,0.2,6745.73,6817.71,NaN,2025.12.19 16:44:12,6818.28,0.0,-0.48,-14.51
1780,2025.12.19 20:00:01,475971400,SP500,buy,0.2,6835.58,6774.69,6925.74,2025.12.24 18:12:28,6925.83,0.0,-1.20,18.05
1781,2025.12.22 01:05:01,476051251,SP500,buy,0.2,6850.88,6789.23,6937.81,2025.12.26 01:14:03,6937.92,0.0,-0.96,17.41
1782,2025.12.29 02:00:01,478335560,US30,buy,0.02,48733.12,48714.21,48809.46,2025.12.29 04:57:51,48714.18,0.0,0.00,-0.38

In [75]:
# print unique values in Volume column
print(df['Volume'].unique())

['0.01' '0.02' '0.05' '0.17' '0.1' '0.03' '0.25' '0.3' '0.2']

In [74]:
# if df.Volumn contain "/", keep only part before "/" and strip spaces
df['Volume'] = df['Volume'].astype(str).apply(lambda x: x.split('/')[0].strip() if '/' in x else x)

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1783 entries, 0 to 1782
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Open Time   1783 non-null   object
 1   Position    1783 non-null   object
 2   Symbol      1783 non-null   object
 3   Type        1783 non-null   object
 4   Volume      1783 non-null   object
 5   Price       1783 non-null   object
 6   S / L       1495 non-null   object
 7   T / P       1468 non-null   float64
 8   Close Time  1783 non-null   object
 9   Price2      1783 non-null   float64
 10  Commission  1783 non-null   float64
 11  Swap        1783 non-null   float64
 12  Profit      1783 non-null   float64
dtypes: float64(5), object(8)
memory usage: 181.2+ KB

In [ ]:
# ==================================================================
"""
from df.tail() check first row with SumSummary:	Summary:	Summary:
cancel all rows from that row onwards, indicating the RangeIndex num
"""
# ==================================================================
;

''

In [ ]:
"""conditions depending on data, check data length first"""
# drop rows indicating correct RangeIndex (with iloc)
up_to_row = 1784  # adjust this number based on actual data
df = df.iloc[:up_to_row]

In [78]:
df.tail(10)

,Open Time,Position,Symbol,Type,Volume,Price,S / L,T / P,Close Time,Price2,Commission,Swap,Profit
1773,2025.12.11 04:00:00,471701268,SP500,buy,0.2,6864.26,6803.16,NaN,2025.12.12 18:38:15,6802.64,0.0,-0.24,-12.32
1774,2025.12.11 05:00:01,471728151,SP500,sell,0.2,6844.74,6905.98,6754.93,2025.12.11 23:06:18,6905.95,0.0,0.00,-12.24
1775,2025.12.11 18:00:00,472196779,SP500,buy,0.2,6868.36,6805.25,6945.29,2025.12.12 18:37:53,6804.84,0.0,-0.24,-12.70
1776,2025.12.12 05:00:02,472381926,SP500,buy,0.2,6906.56,6843.19,NaN,2025.12.12 17:30:04,6842.73,0.0,0.00,-12.77
1777,2025.12.12 18:00:00,472842578,SP500,sell,0.2,6825.75,6895.96,NaN,2025.12.19 22:00:00,6835.27,0.0,-1.68,-1.90
1778,2025.12.15 17:00:00,473463511,SP500,buy,0.2,6834.05,6773.86,NaN,2025.12.16 09:44:06,6773.75,0.0,-0.24,-12.06
1779,2025.12.17 20:00:00,474851918,SP500,sell,0.2,6745.73,6817.71,NaN,2025.12.19 16:44:12,6818.28,0.0,-0.48,-14.51
1780,2025.12.19 20:00:01,475971400,SP500,buy,0.2,6835.58,6774.69,6925.74,2025.12.24 18:12:28,6925.83,0.0,-1.20,18.05
1781,2025.12.22 01:05:01,476051251,SP500,buy,0.2,6850.88,6789.23,6937.81,2025.12.26 01:14:03,6937.92,0.0,-0.96,17.41
1782,2025.12.29 02:00:01,478335560,US30,buy,0.02,48733.12,48714.21,48809.46,2025.12.29 04:57:51,48714.18,0.0,0.00,-0.38

In [79]:
df.shape

(1783, 13)

In [80]:
# download df to csv
df.to_csv('check.csv')

In [ ]:
ò

NameError: name 'ò' is not defined

In [ ]:
"""conditions always valid"""

"""
drop rows where 'Open Time' and 'Close Time' have the following values:
Closed P/L:
Open Trades:
Open Time
Working Orders:
No transactions
0.00
""";
# drop strings in 'Open Time' and 'Close Time' columns
strings_to_drop = ['Closed P/L:', 'Open Trades:', 'Open Time', 'Working Orders:', 'No transactions', '0.00']
df = df[~df['Open Time'].isin(strings_to_drop)]
df = df[~df['Close Time'].isin(strings_to_drop)]

"""
drop rows where 'Type' have the following values:
balance
""";
# drop strings in 'Type' column
df = df[~df['Type'].isin(['balance'])]

# drop rows where 'Ticket' is nan
df = df.dropna(subset=['Ticket'])      

print(df.shape)

ValueError: cannot reindex on an axis with duplicate labels

In [ ]:
.

In [ ]:
"""
drop rows where 'Commission' contains the following values:
cancelled
Floating P/L:
"from #"
"Portfolio"
"folio"  
"to #"
[tp]
[sl]
""";

# drop rows where Commission column contains any of these strings
strings_to_drop_commission = ['cancelled', 'Floating P/L:', 'from #', 'Portfolio', 'folio', 'to #', '[tp]', '[sl]']

# Use str.contains with regex OR pattern to match any of the strings
pattern = '|'.join(strings_to_drop_commission)
df = df[~df['Commission'].str.contains(pattern, case=False, na=False)]

In [ ]:
# # print df.Commission.unique()
# print(df.Commission.unique())

In [ ]:
# convert Open Time and Close Time to datetime
df['Open Time'] = pd.to_datetime(df['Open Time'])
df['Close Time'] = pd.to_datetime(df['Close Time'])

# drop rows where 'Open Time' is nan
df = df.dropna(subset=['Open Time'])

# replace rows where 'Close Time' is nan with 'Close Time' = 'Open Time' + 4 hours
df['Close Time'] = df['Close Time'].fillna(df['Open Time'] + pd.Timedelta(hours=4))

In [ ]:
# df.head()

In [ ]:
# df.tail(20)

In [ ]:
# # print df.Profit.unique()
# print(df.Profit.unique())

In [ ]:
# clean Profit column before converting to float
# remove spaces used as thousands separators
df['Profit'] = df['Profit'].astype(str).str.replace(' ', '', regex=False)

# convert cleaned dataframe to proper Dtypes
df = df.astype({
    'Size': 'float64',
    # check if 'Ticket' can be converted to int, if not use 'str' instead
    'Ticket': 'int64',
    'S / L': 'float64',
    'T / P': 'float64',
    'Price': 'float64',
    'Price2': 'float64',
    'Commission': 'float64',
    'Swap': 'float64',
    'Profit': 'float64'
})

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 671 entries, 1 to 1344
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Ticket      671 non-null    int64
 1   Open Time   671 non-null    datetime64[ns]
 2   Type        671 non-null    object
 3   Size        671 non-null    float64
 4   Item        671 non-null    object
 5   Price       671 non-null    float64
 6   S / L       671 non-null    float64
 7   T / P       671 non-null    float64
 8   Close Time  671 non-null    datetime64[ns]
 9   Price2      671 non-null    float64
 10  Commission  671 non-null    float64
 11  Swap        671 non-null    float64
 12  Profit      671 non-null    float64
dtypes: datetime64[ns](2), float64(8), int64(1), object(2)
memory usage: 73.4+ KB

In [ ]:
# print shape of cleaned dataframe
print(f"Cleaned DataFrame shape: {df.shape}")

# print column names
print("Column names:", df.columns.tolist())

Cleaned DataFrame shape: (671, 13)
Column names: ['Ticket', 'Open Time', 'Type', 'Size', 'Item', 'Price', 'S / L', 'T / P', 'Close Time', 'Price2', 'Commission', 'Swap', 'Profit']

In [ ]:
# ==================================================================
"""
rename cleaned dataframe to clean Excel file name in the next cell
""";
# ==================================================================

In [ ]:
# download cleaned dataframe to excel
cleaned_excel_output = os.path.join(download_path, "cleaned_excel_output.xlsx")

df.to_excel(cleaned_excel_output, index=False)