In [21]:
import pandas as pd
import os
from dotenv import load_dotenv

# Load environment variables (override existing)
load_dotenv(override=True)

True

In [22]:
# Get paths from environment variables
from urllib.parse import unquote

base_path = os.getenv('HTML_PATH')
download_path = os.getenv('DOWNLOAD_PATH')

# Override with specific file path
base_path = r"file:///C:/Users/calli/Downloads/PROP-database-new/da_aggiungere/5%25/ch/100/ReportHistory-25420108.html"

# Handle file:// URI format - convert to regular path
if base_path.startswith('file:///'):
    # Remove file:/// prefix and decode URL encoding (e.g., %20 -> space, %25 -> %)
    path = unquote(base_path[8:])  # Remove 'file:///' - this is already the full file path
elif os.path.isfile(base_path):
    # If base_path is already a file, use it directly
    path = base_path
else:
    # If it's a directory, join with filename
    path = os.path.join(base_path, "DetailedStatement.htm")

print(f"Path: {path}")

Path: C:/Users/calli/Downloads/PROP-database-new/da_aggiungere/5%/ch/100/ReportHistory-25420108.html

In [23]:
# Check if file exists before reading
if not os.path.exists(path):
    print(f"Error: HTML file not found at path")
else:
    # Read HTML file
    tables = pd.read_html(path)
    
    # Check if tables are found
    if not tables:
        print("No tables found in the HTML file.")
    else:
        print(f"Found {len(tables)} tables in the HTML file.")
        for i, table in enumerate(tables, 1):
            print(f"Table {i}: {table.shape[0]} rows x {table.shape[1]} columns")

Found 1 tables in the HTML file.
Table 1: 2082 rows x 22 columns

In [24]:
def html_to_excel(html_file, excel_file):
    try:
        # Read HTML tables from the file
        tables = pd.read_html(html_file)
        if not tables:
            print("No tables found in the HTML file.")
            return
        
        # Save each table to a separate sheet in Excel
        with pd.ExcelWriter(excel_file, engine='openpyxl') as writer:
            for idx, table in enumerate(tables, start=1):
                sheet_name = f"Sheet{idx}"
                table.to_excel(writer, sheet_name=sheet_name, index=False)
        
        print(f"Conversion successful!")
    
    except FileNotFoundError:
        print(f"Error: File '{html_file}' not found.")
    except ValueError as e:
        print(f"Error reading HTML: {e}")
    except Exception as e:
        print(f"Unexpected error: {e}")

# Convert the HTML file to Excel
if os.path.exists(path):
    excel_output = os.path.join(download_path, "converted_tables.xlsx")
    html_to_excel(path, excel_output)
else:
    print("Cannot convert: HTML file not found.")

Conversion successful!

In [25]:
# read converted csv file
df = pd.read_excel(excel_output, sheet_name='Sheet1')
df.head(10)

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,...,Trade History Report,Trade History Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Name:,Name:,Name:,Name:,HS2-100K Simone Calligaro,HS2-100K Simone Calligaro,HS2-100K Simone Calligaro,HS2-100K Simone Calligaro,HS2-100K Simone Calligaro,HS2-100K Simone Calligaro,...,HS2-100K Simone Calligaro,HS2-100K Simone Calligaro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Account:,Account:,Account:,Account:,"25420108 (USD, FivePercentOnline-Real, demo, H...","25420108 (USD, FivePercentOnline-Real, demo, H...","25420108 (USD, FivePercentOnline-Real, demo, H...","25420108 (USD, FivePercentOnline-Real, demo, H...","25420108 (USD, FivePercentOnline-Real, demo, H...","25420108 (USD, FivePercentOnline-Real, demo, H...",...,"25420108 (USD, FivePercentOnline-Real, demo, H...","25420108 (USD, FivePercentOnline-Real, demo, H...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Company:,Company:,Company:,Company:,Five Percent Online Ltd,Five Percent Online Ltd,Five Percent Online Ltd,Five Percent Online Ltd,Five Percent Online Ltd,Five Percent Online Ltd,...,Five Percent Online Ltd,Five Percent Online Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Date:,Date:,Date:,Date:,2025.12.31 06:25,2025.12.31 06:25,2025.12.31 06:25,2025.12.31 06:25,2025.12.31 06:25,2025.12.31 06:25,...,2025.12.31 06:25,2025.12.31 06:25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Positions,Positions,Positions,Positions,Positions,Positions,Positions,Positions,Positions,Positions,...,Positions,Positions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Time,Position,Symbol,Type,Volume,Price,S / L,T / P,Time,Price,...,Profit,Profit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2025.06.30 04:00:00,396840040,US30,buy,192147,192147,192147,192147,192147,192147,...,0.07,44031.69,NaN,NaN,2025.08.07 21:21:43,43893.52,0.00,-6.84,-9.67,-9.67
9,2025.06.30 08:00:00,396903188,XAUUSD,sell,203130039,203130039,203130039,203130039,203130039,203130039,...,0.02,3285.56,3328.74,3213.36,2025.07.01 08:14:09,3328.75,-0.08,-0.46,-86.38,-86.38

In [26]:
df.shape

(2081, 22)

In [27]:
# drop columns index 4 to 11
df.drop(df.columns[4:12], axis=1, inplace=True)
df.head(10)

,0,1,2,3,12,13,14,15,16,17,18,19,20,21
0,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,Trade History Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Name:,Name:,Name:,Name:,HS2-100K Simone Calligaro,HS2-100K Simone Calligaro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Account:,Account:,Account:,Account:,"25420108 (USD, FivePercentOnline-Real, demo, H...","25420108 (USD, FivePercentOnline-Real, demo, H...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Company:,Company:,Company:,Company:,Five Percent Online Ltd,Five Percent Online Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Date:,Date:,Date:,Date:,2025.12.31 06:25,2025.12.31 06:25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Positions,Positions,Positions,Positions,Positions,Positions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Time,Position,Symbol,Type,Profit,Profit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2025.06.30 04:00:00,396840040,US30,buy,0.07,44031.69,NaN,NaN,2025.08.07 21:21:43,43893.52,0.00,-6.84,-9.67,-9.67
9,2025.06.30 08:00:00,396903188,XAUUSD,sell,0.02,3285.56,3328.74,3213.36,2025.07.01 08:14:09,3328.75,-0.08,-0.46,-86.38,-86.38

In [28]:
df.shape

(2081, 14)

In [29]:
# keep df from row 8 only
df = df.iloc[8:]
df.head(10)

,0,1,2,3,12,13,14,15,16,17,18,19,20,21
8,2025.06.30 04:00:00,396840040,US30,buy,0.07,44031.69,NaN,NaN,2025.08.07 21:21:43,43893.52,0.00,-6.84,-9.67,-9.67
9,2025.06.30 08:00:00,396903188,XAUUSD,sell,0.02,3285.56,3328.74,3213.36,2025.07.01 08:14:09,3328.75,-0.08,-0.46,-86.38,-86.38
10,2025.07.01 04:00:00,397412363,XAUUSD,buy,0.03,3315.04,3274.65,3374.65,2025.07.14 10:30:01,3374.68,-0.12,-16.38,178.92,178.92
11,2025.07.01 05:00:00,397434985,US30,sell,0.11,44126.91,44759.44,NaN,2025.07.02 10:00:00,44655.39,0.00,-0.66,-58.13,-58.13
12,2025.07.01 06:00:00,397450171,US30,sell,0.11,44061.51,44810.97,43201.08,2025.07.03 17:36:58,44811.69,0.00,-1.32,-82.52,-82.52
13,2025.07.01 08:00:00,397479851,XAUUSD,buy,0.03,3323.20,3282.90,3382.90,2025.07.09 11:37:58,3282.74,-0.12,-10.08,-121.38,-121.38
14,2025.07.01 16:00:00,397760599,XAUUSD,buy,0.03,3354.88,3306.91,3417.89,2025.07.07 04:21:23,3306.89,-0.12,-7.56,-143.97,-143.97
15,2025.07.01 16:00:00,397760712,XAUUSD,buy,0.03,3355.47,3314.62,3414.62,2025.07.03 15:43:26,3314.74,-0.12,-5.04,-122.19,-122.19
16,2025.07.01 20:00:00,397947791,US30,sell,0.11,44425.91,45127.03,43654.69,2025.07.08 15:00:00,44389.69,0.00,-4.62,3.98,3.98
17,2025.07.02 02:00:01,398007842,US30,sell,0.11,44527.21,45070.42,43566.50,2025.07.10 18:00:00,44658.89,0.00,-5.28,-14.48,-14.48

In [30]:
# Columns are already correctly named in the previous cell
df.columns.tolist()

[0, 1, 2, 3, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [31]:
# rename columns to Time	Position	Symbol	Type	Volume	Price	S / L	T / P	Time	Price	Commission	Swap	Profit Extra
df.columns = ['Time', 'Position', 'Symbol', 'Type', 'Volume', 'Price', 'S / L', 'T / P', 'Time2', 'Price2', 'Commission', 'Swap', 'Profit', 'Extra']
df.head(10)

,Time,Position,Symbol,Type,Volume,Price,S / L,T / P,Time2,Price2,Commission,Swap,Profit,Extra
8,2025.06.30 04:00:00,396840040,US30,buy,0.07,44031.69,NaN,NaN,2025.08.07 21:21:43,43893.52,0.00,-6.84,-9.67,-9.67
9,2025.06.30 08:00:00,396903188,XAUUSD,sell,0.02,3285.56,3328.74,3213.36,2025.07.01 08:14:09,3328.75,-0.08,-0.46,-86.38,-86.38
10,2025.07.01 04:00:00,397412363,XAUUSD,buy,0.03,3315.04,3274.65,3374.65,2025.07.14 10:30:01,3374.68,-0.12,-16.38,178.92,178.92
11,2025.07.01 05:00:00,397434985,US30,sell,0.11,44126.91,44759.44,NaN,2025.07.02 10:00:00,44655.39,0.00,-0.66,-58.13,-58.13
12,2025.07.01 06:00:00,397450171,US30,sell,0.11,44061.51,44810.97,43201.08,2025.07.03 17:36:58,44811.69,0.00,-1.32,-82.52,-82.52
13,2025.07.01 08:00:00,397479851,XAUUSD,buy,0.03,3323.20,3282.90,3382.90,2025.07.09 11:37:58,3282.74,-0.12,-10.08,-121.38,-121.38
14,2025.07.01 16:00:00,397760599,XAUUSD,buy,0.03,3354.88,3306.91,3417.89,2025.07.07 04:21:23,3306.89,-0.12,-7.56,-143.97,-143.97
15,2025.07.01 16:00:00,397760712,XAUUSD,buy,0.03,3355.47,3314.62,3414.62,2025.07.03 15:43:26,3314.74,-0.12,-5.04,-122.19,-122.19
16,2025.07.01 20:00:00,397947791,US30,sell,0.11,44425.91,45127.03,43654.69,2025.07.08 15:00:00,44389.69,0.00,-4.62,3.98,3.98
17,2025.07.02 02:00:01,398007842,US30,sell,0.11,44527.21,45070.42,43566.50,2025.07.10 18:00:00,44658.89,0.00,-5.28,-14.48,-14.48

In [32]:
# print sum of Profit and Extra columns to compare values
print("Sum of Profit column:", df['Profit'].sum())
print("Sum of Extra column:", df['Extra'].sum())

Sum of Profit column: -1774.4899999999993
Sum of Extra column: -1774.4899999999993

In [33]:
# drop column Extra if Sum of Profit column and Sum of Extra column are the same
if df['Profit'].sum() == df['Extra'].sum():
    df.drop(columns=['Extra'], inplace=True)

# rename Time to Open Time and Time2 to Close Time
df.rename(columns={'Time': 'Open Time', 'Time2': 'Close Time'}, inplace=True)

In [34]:
df.head()

,Open Time,Position,Symbol,Type,Volume,Price,S / L,T / P,Close Time,Price2,Commission,Swap,Profit
8,2025.06.30 04:00:00,396840040,US30,buy,0.07,44031.69,NaN,NaN,2025.08.07 21:21:43,43893.52,0.00,-6.84,-9.67
9,2025.06.30 08:00:00,396903188,XAUUSD,sell,0.02,3285.56,3328.74,3213.36,2025.07.01 08:14:09,3328.75,-0.08,-0.46,-86.38
10,2025.07.01 04:00:00,397412363,XAUUSD,buy,0.03,3315.04,3274.65,3374.65,2025.07.14 10:30:01,3374.68,-0.12,-16.38,178.92
11,2025.07.01 05:00:00,397434985,US30,sell,0.11,44126.91,44759.44,NaN,2025.07.02 10:00:00,44655.39,0.00,-0.66,-58.13
12,2025.07.01 06:00:00,397450171,US30,sell,0.11,44061.51,44810.97,43201.08,2025.07.03 17:36:58,44811.69,0.00,-1.32,-82.52

In [35]:
df.tail()

,Open Time,Position,Symbol,Type,Volume,Price,S / L,T / P,Close Time,Price2,Commission,Swap,Profit
2076,NaN,NaN,NaN,NaN,-323.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2077,NaN,NaN,NaN,NaN,-49.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2078,NaN,NaN,NaN,NaN,17 (-428.83),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2079,NaN,NaN,NaN,NaN,-1 248.70 (9),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2080,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
df.shape

(2073, 13)

In [37]:
"""
Check case by case the following conditions:
"""
# 478733279 is currently the last open position in the html statement
# print row where Ticket is 479721516
df[df['Position'].astype(str) == '479721516']

,Open Time,Position,Symbol,Type,Volume,Price,S / L,T / P,Close Time,Price2,Commission,Swap,Profit
395,2025.12.30 23:00:01,479721516,NAS100,buy,0.1,25464.76,25311.74,NaN,2025.12.31 14:00:00,25398.34,0.0,-0.3,-6.64
1178,2025.12.30 23:00:00,479721516,NAS100,buy,260050,260050,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
"""
Check case by case the following conditions:
"""

# keep rows up to 388
df = df.iloc[:388].reset_index(drop=True)

In [39]:
df.tail(10)

,Open Time,Position,Symbol,Type,Volume,Price,S / L,T / P,Close Time,Price2,Commission,Swap,Profit
378,2025.12.30 05:00:00,479160942,NAS100,sell,0.1,25497.64,25728.72,NaN,2025.12.30 06:00:00,25525.16,0.0,0.0,-2.75
379,2025.12.30 07:00:00,479195639,NAS100,buy,0.1,25537.96,25370.45,NaN,2025.12.31 08:27:17,25370.04,0.0,-0.3,-16.79
380,2025.12.30 08:00:00,479219350,NAS100,buy,0.1,25533.16,25362.41,25849.88,2025.12.31 10:31:20,25362.04,0.0,-0.3,-17.11
381,2025.12.30 10:00:00,479281324,NAS100,buy,0.1,25492.36,25300.41,NaN,2025.12.30 11:00:00,25525.14,0.0,0.0,3.28
382,2025.12.30 14:00:00,479412996,NAS100,buy,0.1,25521.16,25328.21,NaN,2025.12.30 15:00:00,25513.34,0.0,0.0,-0.78
383,2025.12.30 18:00:00,479615122,NAS100,buy,0.1,25532.16,25393.96,25791.07,2025.12.31 03:00:30,25393.54,0.0,-0.3,-13.86
384,2025.12.30 20:00:00,479673174,NAS100,buy,0.1,25517.36,25325.31,NaN,2025.12.30 21:00:00,25519.54,0.0,0.0,0.22
385,2025.12.30 20:00:00,479673346,NAS100,buy,0.1,25517.66,25360.52,25765.57,2025.12.31 10:31:29,25359.14,0.0,-0.3,-15.85
386,2025.12.30 23:00:00,479721347,NAS100,buy,0.1,25468.06,25275.46,NaN,2025.12.31 01:05:00,25471.34,0.0,-0.3,0.33
387,2025.12.30 23:00:01,479721516,NAS100,buy,0.1,25464.76,25311.74,NaN,2025.12.31 14:00:00,25398.34,0.0,-0.3,-6.64

In [43]:
# print unique values in Volume column
print(df['Volume'].unique())

['0.07' '0.02' '0.03' '0.11' '0.08' '0.15' '0.1' '0.2' '0.14' '0.01' '0.5'
 '0.45' '0.18' '0.13' '0.12' '0.05']

In [42]:
# if df.Volumn contain "/", keep only part before "/" and strip spaces
df['Volume'] = df['Volume'].astype(str).apply(lambda x: x.split('/')[0].strip() if '/' in x else x)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Open Time   388 non-null    object
 1   Position    388 non-null    object
 2   Symbol      388 non-null    object
 3   Type        388 non-null    object
 4   Volume      388 non-null    object
 5   Price       388 non-null    object
 6   S / L       380 non-null    object
 7   T / P       193 non-null    float64
 8   Close Time  388 non-null    object
 9   Price2      388 non-null    float64
 10  Commission  388 non-null    float64
 11  Swap        388 non-null    float64
 12  Profit      388 non-null    float64
dtypes: float64(5), object(8)
memory usage: 39.5+ KB

In [ ]:
# # ==================================================================
# """
# from df.tail() check first row with SumSummary:	Summary:	Summary:
# cancel all rows from that row onwards, indicating the RangeIndex num
# """
# # ==================================================================
# ;

''

In [ ]:
# """conditions depending on data, check data length first"""
# # drop rows indicating correct RangeIndex (with iloc)
# up_to_row = 1784  # adjust this number based on actual data
# df = df.iloc[:up_to_row]

In [45]:
df.tail(10)

,Open Time,Position,Symbol,Type,Volume,Price,S / L,T / P,Close Time,Price2,Commission,Swap,Profit
378,2025.12.30 05:00:00,479160942,NAS100,sell,0.1,25497.64,25728.72,NaN,2025.12.30 06:00:00,25525.16,0.0,0.0,-2.75
379,2025.12.30 07:00:00,479195639,NAS100,buy,0.1,25537.96,25370.45,NaN,2025.12.31 08:27:17,25370.04,0.0,-0.3,-16.79
380,2025.12.30 08:00:00,479219350,NAS100,buy,0.1,25533.16,25362.41,25849.88,2025.12.31 10:31:20,25362.04,0.0,-0.3,-17.11
381,2025.12.30 10:00:00,479281324,NAS100,buy,0.1,25492.36,25300.41,NaN,2025.12.30 11:00:00,25525.14,0.0,0.0,3.28
382,2025.12.30 14:00:00,479412996,NAS100,buy,0.1,25521.16,25328.21,NaN,2025.12.30 15:00:00,25513.34,0.0,0.0,-0.78
383,2025.12.30 18:00:00,479615122,NAS100,buy,0.1,25532.16,25393.96,25791.07,2025.12.31 03:00:30,25393.54,0.0,-0.3,-13.86
384,2025.12.30 20:00:00,479673174,NAS100,buy,0.1,25517.36,25325.31,NaN,2025.12.30 21:00:00,25519.54,0.0,0.0,0.22
385,2025.12.30 20:00:00,479673346,NAS100,buy,0.1,25517.66,25360.52,25765.57,2025.12.31 10:31:29,25359.14,0.0,-0.3,-15.85
386,2025.12.30 23:00:00,479721347,NAS100,buy,0.1,25468.06,25275.46,NaN,2025.12.31 01:05:00,25471.34,0.0,-0.3,0.33
387,2025.12.30 23:00:01,479721516,NAS100,buy,0.1,25464.76,25311.74,NaN,2025.12.31 14:00:00,25398.34,0.0,-0.3,-6.64

In [46]:
df.shape

(388, 13)

In [ ]:
# """conditions always valid"""

# """
# drop rows where 'Open Time' and 'Close Time' have the following values:
# Closed P/L:
# Open Trades:
# Open Time
# Working Orders:
# No transactions
# 0.00
# """;
# # drop strings in 'Open Time' and 'Close Time' columns
# strings_to_drop = ['Closed P/L:', 'Open Trades:', 'Open Time', 'Working Orders:', 'No transactions', '0.00']
# df = df[~df['Open Time'].isin(strings_to_drop)]
# df = df[~df['Close Time'].isin(strings_to_drop)]

# """
# drop rows where 'Type' have the following values:
# balance
# """;
# # drop strings in 'Type' column
# df = df[~df['Type'].isin(['balance'])]

# # drop rows where 'Ticket' is nan
# df = df.dropna(subset=['Ticket'])      

# print(df.shape)

In [ ]:
# """
# drop rows where 'Commission' contains the following values:
# cancelled
# Floating P/L:
# "from #"
# "Portfolio"
# "folio"  
# "to #"
# [tp]
# [sl]
# """;

# # drop rows where Commission column contains any of these strings
# strings_to_drop_commission = ['cancelled', 'Floating P/L:', 'from #', 'Portfolio', 'folio', 'to #', '[tp]', '[sl]']

# # Use str.contains with regex OR pattern to match any of the strings
# pattern = '|'.join(strings_to_drop_commission)
# df = df[~df['Commission'].str.contains(pattern, case=False, na=False)]

In [ ]:
# # print df.Commission.unique()
# print(df.Commission.unique())

In [47]:
# convert Open Time and Close Time to datetime
df['Open Time'] = pd.to_datetime(df['Open Time'])
df['Close Time'] = pd.to_datetime(df['Close Time'])

# drop rows where 'Open Time' is nan
df = df.dropna(subset=['Open Time'])

# replace rows where 'Close Time' is nan with 'Close Time' = 'Open Time' + 4 hours
df['Close Time'] = df['Close Time'].fillna(df['Open Time'] + pd.Timedelta(hours=4))

In [48]:
df.head()

,Open Time,Position,Symbol,Type,Volume,Price,S / L,T / P,Close Time,Price2,Commission,Swap,Profit
0,2025-06-30 04:00:00,396840040,US30,buy,0.07,44031.69,NaN,NaN,2025-08-07 21:21:43,43893.52,0.00,-6.84,-9.67
1,2025-06-30 08:00:00,396903188,XAUUSD,sell,0.02,3285.56,3328.74,3213.36,2025-07-01 08:14:09,3328.75,-0.08,-0.46,-86.38
2,2025-07-01 04:00:00,397412363,XAUUSD,buy,0.03,3315.04,3274.65,3374.65,2025-07-14 10:30:01,3374.68,-0.12,-16.38,178.92
3,2025-07-01 05:00:00,397434985,US30,sell,0.11,44126.91,44759.44,NaN,2025-07-02 10:00:00,44655.39,0.00,-0.66,-58.13
4,2025-07-01 06:00:00,397450171,US30,sell,0.11,44061.51,44810.97,43201.08,2025-07-03 17:36:58,44811.69,0.00,-1.32,-82.52

In [ ]:
# df.tail(20)

In [ ]:
# # print df.Profit.unique()
# print(df.Profit.unique())

In [49]:
# clean Profit column before converting to float
# remove spaces used as thousands separators
df['Profit'] = df['Profit'].astype(str).str.replace(' ', '', regex=False)

# convert cleaned dataframe to proper Dtypes
df = df.astype({
    'Volume': 'float64',
    # check if 'Ticket' can be converted to int, if not use 'str' instead
    'Position': 'int64',
    'S / L': 'float64',
    'T / P': 'float64',
    'Price': 'float64',
    'Price2': 'float64',
    'Commission': 'float64',
    'Swap': 'float64',
    'Profit': 'float64'
})

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Open Time   388 non-null    datetime64[ns]
 1   Position    388 non-null    int64
 2   Symbol      388 non-null    object
 3   Type        388 non-null    object
 4   Volume      388 non-null    float64
 5   Price       388 non-null    float64
 6   S / L       380 non-null    float64
 7   T / P       193 non-null    float64
 8   Close Time  388 non-null    datetime64[ns]
 9   Price2      388 non-null    float64
 10  Commission  388 non-null    float64
 11  Swap        388 non-null    float64
 12  Profit      388 non-null    float64
dtypes: datetime64[ns](2), float64(8), int64(1), object(2)
memory usage: 39.5+ KB

In [51]:
# print shape of cleaned dataframe
print(f"Cleaned DataFrame shape: {df.shape}")

# print column names
print("Column names:", df.columns.tolist())

Cleaned DataFrame shape: (388, 13)
Column names: ['Open Time', 'Position', 'Symbol', 'Type', 'Volume', 'Price', 'S / L', 'T / P', 'Close Time', 'Price2', 'Commission', 'Swap', 'Profit']

In [ ]:
# # ==================================================================
# """
# rename cleaned dataframe to clean Excel file name in the next cell
# """;
# # ==================================================================

In [52]:
# download cleaned dataframe to excel
cleaned_excel_output = os.path.join(download_path, "cleaned_excel_output_100k_5ers_ch.xlsx")

df.to_excel(cleaned_excel_output, index=False)